apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-j
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: app-j
  template:
    metadata:
      labels:
        app.kubernetes.io/name: app-j
    spec:
      containers:
      - name: app
        image: registry:5000/server-jaeger:0.1.0
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          runAsUser: 1000
          runAsGroup: 1000
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
          requests:
            cpu: 200m
            memory: 128Mi
        ports:
          - containerPort: 3030
            protocol: TCP
