FROM golang:1.19 AS builder
ENV GO111MODULE=on GOPROXY=https://goproxy.io,direct
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
ARG SERVER_SRC=server
COPY ${SERVER_SRC}.go ./
RUN CGO_ENABLED=0 GOOS=linux go build -o /server



FROM alpine:3.18.3 AS release
# RUN apk add --no-cache libc6-compat
WORKDIR /
COPY --from=builder /server /server
EXPOSE 3030
USER nonroot:nonroot
ENTRYPOINT ["/server"]
